### ISSUE TITLE
[Question] Process.Platform

### ISSUE THREAD

**Issue by frankhale** [tht13/electrino#6]
We can get some more pertinent information about the system by changing the Process.Platform getter in RenderAPI.JSProcess:

```csharp
public string Platform
{
  get
  {
    // Might want to extract this into it's own class like: https://www.suchan.cz/2015/08/uwp-quick-tip-getting-device-os-and-app-info/

    string deviceFamilyVersion = AnalyticsInfo.VersionInfo.DeviceFamilyVersion;
    ulong version = ulong.Parse(deviceFamilyVersion);
    ulong major = (version & 0xFFFF000000000000L) >> 48;
    ulong minor = (version & 0x0000FFFF00000000L) >> 32;
    ulong build = (version & 0x00000000FFFF0000L) >> 16;
    ulong revision = (version & 0x000000000000FFFFL);
    var osVersion = $"{major}.{minor}.{build}.{revision}";

    AnalyticsVersionInfo ai = AnalyticsInfo.VersionInfo;
    
    return $"{ai.DeviceFamily} {osVersion} {Package.Current.Id.Architecture.ToString()}";
  }
}
``` 

Here is a screenshot of what the output looks like:

![electrino_screenshot](https://cloud.githubusercontent.com/assets/190154/26645823/74d18b7a-4607-11e7-82e0-95080a3cabad.png)

Do you think this would be a good change?

**Comment by tht13** [comment]
Since the goal of Electrino is to match the Electron (and thus Node) API as closely as possible I think we should do this the "node" way. The OS version `10.0.15063` would be under `require("os").release()` and `X86` under `process.arch`. I can't seem to find an appropriate place to put `Windows.Desktop` yet by just looking at it. 

Expanding on API coverage is definitely what we need to do though. Although I'm not sure about replicating the entire Node API, I have been looking at the work in [node-chakracore](https://github.com/nodejs/node-chakracore) and wondering if we could somehow adopt that on top of/into this.

**Comment by tht13** [comment]
Checkout c278bee37, this adds your changes in a Node/Electron API method.

**Comment by frankhale** [comment]
Okay cool that sounds good.
